services:

  flux_se.sylius_payum_stripe.state_machine.refund:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\StateMachine\RefundOrderProcessor
    arguments:
      $commandBus: '@sylius.command_bus'

  flux_se.sylius_payum_stripe.state_machine.cancel:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\StateMachine\CancelOrderProcessor
    arguments:
      $commandBus: '@sylius.command_bus'

  flux_se.sylius_payum_stripe.state_machine.capture_authorized:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\StateMachine\CaptureAuthorizedOrderProcessor
    arguments:
      $commandBus: '@sylius.command_bus'
