services:

  flux_se.sylius_payum_stripe.action.stripe_js.convert_payment:
    public: true
    class: FluxSE\SyliusPayumStripePlugin\Action\StripeJs\ConvertPaymentAction
    arguments:
      $detailsProvider: '@flux_se.sylius_payum_stripe.provider.stripe_js.details'
    tags:
      - name: payum.action
        factory: stripe_js
        alias: flux_se.sylius_payum_stripe.convert_payment
