services:

  flux_se.sylius_payum_stripe.api.payment_provider.stripe_checkout_session:
    class: FluxSE\SyliusPayumStripePlugin\Api\PaymentConfiguration\StripeCheckoutSessionPaymentConfigProvider
    arguments:
      $captureProcessor: '@flux_se.sylius_payum_stripe.api.payum.capture_processor.stripe_js'
      $factoryName: 'stripe_checkout_session'
    tags:
      - name: sylius.api.payment_method_handler

  flux_se.sylius_payum_stripe.api.payum.capture_processor.stripe_checkout_session:
    class: FluxSE\SyliusPayumStripePlugin\Api\Payum\CaptureProcessor
    arguments:
      $payum: '@payum'
      $captureRequestFactory: '@flux_se.sylius_payum_stripe.factory.capture_request'
      $afterUrlProvider: '@flux_se.sylius_payum_stripe.api.payum.after_url.stripe_checkout_session'

  flux_se.sylius_payum_stripe.api.payum.after_url.stripe_checkout_session:
    class: FluxSE\SyliusPayumStripePlugin\Api\Payum\AfterUrlProvider
    arguments:
      $afterPath: 'sylius_shop_homepage'
